HowManyDaysThatLogsShouldSave = 30 #存储多少天,之前的会drop table
LogModelChanSize = 65536 #越大越不会锁死
GRPCPort = 12345 #需要与客户端配置一致
HowOftenToInsertDBInSeconds = 1 #距离上一次入库x秒后再次入库
HowManyLogsToInsertDBOnce = 8192 #攒够x条消息则入库
[MySQLConf]
Host='localhost'
Port='3306'
Account='root'
PasswordBase64Str='8FNdkbFImC2tar2r5Oe7eg=='
DatabaseName='test_log'